### ISSUE TITLE
照书的安装步骤搭建环境失败，启动 fj server 报错 服务起不来。。。

### ISSUE THREAD

**Issue by XIRALIP** [ng-nice/code-front-jet#8]
[11:12:01] Starting 'bowerInstall'...
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\fj\node_modules\._bower@1.7.7@bower\lib\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[11:12:02] gulp-notify: [Front Jet Error Report] bower install失败，可能网络有问
题或存在版本冲突，请手动运行bower install命令来解决它。
bower install失败，可能网络有问题或存在版本冲突，请手动运行bower install命令来解
决它。

**Comment by ghost** [comment]
我也遇到这个问题，应该是跟NODE版本升级太快导致的。

**Comment by zhangwilling** [comment]
降级到 5.x即可
